### ISSUE TITLE
Yarn v2 Support

### ISSUE THREAD

**Issue by br0p0p** [c-hive/gha-yarn-cache#10]
Hi, I forked this to add Yarn v2 support.

I think the best solution would be to merge that here and either create a new branch with Yarn v2 support or determine the Yarn version in the code and call either `yarn cache dir` or `yarn config get cacheFolder` whether Yarn v1 or v2 is detected, respectively.

What are your thoughts?

**Comment by thisismydesign** [comment]
Thanks!

Linking the fork for reference: https://github.com/br0p0p/gha-yarn-cache

What does Yarn v2 respond to `yarn cache dir`? Maybe if [this part](https://github.com/c-hive/gha-yarn-cache/blob/dfc06a55a6ea1c3c8ce7fda005ac2df0fad51315/src/restore.js#L27-L29) returns empty then we could try the v2 syntax?

**Comment by br0p0p** [comment]
Running  `yarn cache dir` with Yarn v2 errors:
```sh           
Unknown Syntax Error: Command not found; did you mean:

$ yarn cache clean [--mirror] [--all]
While running cache dir
```

However running `yarn config get cacheFolder` with v1 results in 

```sh
undefined
```

**Comment by br0p0p** [comment]
so, the v2 command (`yarn config get cacheFolder`) could be the default and the v1 command (`yarn cache dir`) could be the fallback if the first result is `undefined`

**Comment by thisismydesign** [comment]
Yes! If you're up for submitting a PR I'd be happy to release a v2 with this functionality.

**Comment by thisismydesign** [comment]
@br0p0p v2 released: https://github.com/c-hive/gha-yarn-cache/releases/tag/v2 Let me know if it works for you.

Thanks for your help!
