### ISSUE TITLE
Error [ERR_STREAM_PREMATURE_CLOSE]: Premature close

### ISSUE THREAD

**Issue by bennycode** [c-hive/gha-yarn-cache#18]
We sometimes get this error during our builds:

```
Run c-hive/gha-yarn-cache@v1
/usr/bin/uname
Linux
/usr/local/bin/yarn cache dir
/home/runner/.cache/yarn/v6
Cache keys: Linux-yarn-cache-46490e93e8e5be3fec3d0477b450057b, Linux-yarn-cache-
Error: Error [ERR_STREAM_PREMATURE_CLOSE]: Premature close
```

Build: https://github.com/wireapp/wire-webapp/runs/3526104613

Is this "Premature close" problem a known bug?

**Comment by thisismydesign** [comment]
If it's a bug, it's not related to this project. Some say Node.js : https://github.com/sindresorhus/got/issues/1003#issuecomment-575951136 but you can find multiple references on google.
