### ISSUE TITLE
Anybody knows why my yarn Link step is taking so long?

### ISSUE THREAD

**Issue by marcofugaro** [c-hive/gha-yarn-cache#20]
I am using this action before running yarn, it works correctly as in the yarn fetch phase is skipped.

However the yarn `Link step` phase still takes a bit:

![image](https://user-images.githubusercontent.com/7217420/144241285-aa671e27-8b62-46d0-ab47-a198c4035c04.png)

Anybody knows why is it taking so long?

The Link step output is full of these logs:

![image](https://user-images.githubusercontent.com/7217420/144241408-4aee4953-8064-44bf-859c-a8260ebd51d0.png)

**Comment by thisismydesign** [comment]
Could be due to the difference between caching `node_modules` and `yarn cache dir` that you can look into. If not, then I think it should be the same with and without the cache.

Closing as this is not really an open issue with this repo. Comments will be open if anyone wants to discuss further.
